# Project settings - General
version: 0.0.1
title: "The Tyee Article Page"
description: ""
baseurl: ""
url: "http://thetyee.github.io/design-article.thetyee.ca/"
logo: 'tyee_logo.png'

# Project settings - Analytics
analytics:
    ga_tracking_id: 'UA-12345-5'

# Project settings - Meta
author: "The Tyee"
robots: "index, follow"
revisit: "1 day"
copyright: "&copy; The Tyee 2015"

# Project settings - Assets
asset_paths:
    img: ""
    js:  ""

# Project settings - URLs
urls:
    display: ''
    privacy: ''
    credits: ''
    credits: ''

# Project settings - Social
social:
    facebook:
        fb_admins:
            - 12345
        og_url:
        og_image:
        og_sitename:
    twitter:
    gplus:

# Jekyll build settings
markdown: kramdown
permalink: pretty
exclude:
  - README.md
  - bower.json
  - package.json
  - node_modules
  - Gruntfile.js
  - gemfile
  - Gemfile.lock
